"""message

Revision ID: 2d562c73be8b
Revises: 
Create Date: 2023-09-05 16:05:44.765890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d562c73be8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users-table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=True),
    sa.Column('user_id_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['users-table.id'], name=op.f('fk_chats_table_user_id_1_users-table')),
    sa.ForeignKeyConstraint(['user_id_2'], ['users-table.id'], name=op.f('fk_chats_table_user_id_2_users-table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings-table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users-table.id'], name=op.f('fk_listings-table_user_id_users-table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats_table.id'], name=op.f('fk_messages_table_chat_id_chats_table')),
    sa.ForeignKeyConstraint(['sender_id'], ['users-table.id'], name=op.f('fk_messages_table_sender_id_users-table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_table')
    op.drop_table('listings-table')
    op.drop_table('chats_table')
    op.drop_table('users-table')
    # ### end Alembic commands ###
